# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://halfoncloud.com/"
# title = "Clarity" # Edit directly from config/_default/languages.toml
copyright = "Copyright © 2025, Radu and the Hugo Authors; all rights reserved."

theme = "hugo-clarity"
disqusShortname = ""

DefaultContentLanguage = "en"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[pagination]
pagerSize = 10
