baseURL = 'https://halfoncloud.com/'
languageCode = 'en-us'
title = 'HalfOnCloud'
copyright = "2026 Radu Bogdan :: HalfOnCloud"
theme = 'terminal'
summaryLength = 100

[markup]
  [markup.highlight]
    style = "paraiso-dark"
    lineNos = false
    noClasses = true
    guessSyntax = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
	
[params]
  themeColor = "orange"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = false
  description = "Tutorials, Automation scripts and Microsoft technology insights"
  author = "Radu Bogdan"

[languages]
  [languages.en]
    languageName = "English"
    [languages.en.params]
      readMore = "Read More"
      readOtherPosts = "Read other posts"
    [languages.en.params.logo]
      logoText = "HalfOnCloud "
      logoCursor = "|"
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 1
    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/posts/"
      weight = 2
    [[languages.en.menu.main]]
      identifier = "privacy"
      name = "Privacy Policy"
      url = "/privacy-policy/"
      weight = 3
	  
[outputs]
  home = ["HTML", "JSON"]