[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Microsoft"
  url = "/categories/microsoft/"
  identifier = "Microsoft"
  weight = 20

[[main]]
  name = "Azure"
  url = "/tags/azure/"
  parent = "Microsoft"
  weight = 21

[[main]]
  name = "Intune"
  url = "/tags/intune/"
  parent = "Microsoft"
  weight = 22

[[main]]
  name = "SCCM"
  url = "/tags/sccm/"
  parent = "Microsoft"
  weight = 23

[[main]]
  name = "EntraID"
  url = "/tags/entraid/"
  parent = "Microsoft"
  weight = 24

[[main]]
  name = "M365"
  url = "/tags/m365/"
  parent = "Microsoft"
  weight = 25

[[main]]
  name = "Virtualization"
  url = "/categories/virtualization/"
  identifier = "Virtualization"
  weight = 30

[[main]]
  name = "VMware"
  url = "/tags/vmware/"
  parent = "Virtualization"
  weight = 31

[[main]]
  name = "Hyper-V"
  url = "/tags/hyperv/"
  parent = "Virtualization"
  weight = 32

[[main]]
  name = "Automation"
  url = "/categories/automation/"
  identifier = "Automation"
  weight = 40

[[main]]
  name = "PowerShell"
  url = "/tags/powershell/"
  parent = "Automation"
  weight = 41

[[main]]
  name = "Scripting"
  url = "/tags/scripting/"
  parent = "Automation"
  weight = 42

[[main]]
  name = "Efficiency"
  url = "/tags/efficiency/"
  parent = "Automation"
  weight = 43

[[main]]
  name = "About"
  url = "/about/"
  weight = 50